ALTER TABLE "Task" ADD COLUMN "canWait" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "AgentRun" ADD COLUMN "quotaDeferred" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "AgentRun" ADD COLUMN "quotaLimited" BOOLEAN NOT NULL DEFAULT false;
