export const queryKeys = {
  me: ["me"] as const,
  catalog: ["catalog"] as const,
  telemetry: ["telemetry"] as const,
  savings: ["telemetry", "savings"] as const,
  projects: ["projects"] as const,
  paletteProjects: ["projects", "palette"] as const,
  project: (id: string) => ["projects", id] as const,
  projectStack: (id: string) => ["projects", id, "stack"] as const,
  tasks: (filter: { projectId?: string; status?: string } = {}) => ["tasks", filter] as const,
  allTasks: ["tasks"] as const,
  paletteTasks: ["tasks", "palette"] as const,
  task: (id: string) => ["task", id] as const,
  run: (id: string) => ["run", id] as const,
  runBlocked: (id: string) => ["run", id, "blocked"] as const,
  tddLoops: (taskId: string) => ["tdd", taskId] as const,
  tddDefaults: (taskId: string) => ["tdd", taskId, "defaults"] as const,
  sessions: (workspaceId: string) => ["sessions", workspaceId] as const,
  workspace: (workspaceId: string) => ["workspace", workspaceId] as const,
  terminals: (workspaceId: string) => ["terminals", workspaceId] as const,
  routerSettings: ["router", "settings"] as const,
  routingRules: ["router", "rules"] as const,
  routingDecisions: ["router", "decisions"] as const,
  routingTelemetry: ["router", "telemetry"] as const,
  routerPreview: (input: object) => ["router", "preview", input] as const,
  githubAccount: ["github", "account"] as const,
  claudeAccount: ["settings", "claude"] as const,
  board: (projectId: string) => ["board", projectId] as const,
  gitIdentity: ["settings", "git"] as const,
  githubRepos: (owner: string) => ["github", "repos", owner] as const,
  githubImport: (jobId: string) => ["github", "import", jobId] as const,
  index: (projectId: string) => ["index", projectId] as const,
  graph: (projectId: string, focus: string | null, depth: number) =>
    ["graph", projectId, focus, depth] as const,
  allGraphs: (projectId: string) => ["graph", projectId] as const,
  fileContext: (projectId: string, path: string, level: number) =>
    ["file-context", projectId, path, level] as const,
  surgeon: (projectId: string, workspaceId: string | null) =>
    ["surgeon", projectId, workspaceId] as const,
  allSurgeon: (projectId: string) => ["surgeon", projectId] as const,
  surgeonCompiled: (projectId: string, workspaceId: string | null, version: string) =>
    ["surgeon", projectId, workspaceId, "compiled", version] as const,
  orchestrations: (projectId: string) => ["orchestrations", projectId] as const,
  orchestration: (id: string) => ["orchestration", id] as const,
  approvals: ["approvals"] as const,
  approvalsPending: ["approvals", "pending"] as const,
  budgets: ["budgets"] as const,
  quota: ["quota"] as const,
  queue: ["queue"] as const,
  notifications: ["settings", "notifications"] as const,
  mission: ["mission"] as const,
  backups: ["backups"] as const,
};
